'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QM.PDA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respuesta incompleta.
        '''</summary>
        Friend ReadOnly Property action_msbRequiredCap() As String
            Get
                Return ResourceManager.GetString("action_msbRequiredCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe seleccionar una operación.
        '''</summary>
        Friend ReadOnly Property action_msbRequiredMsg() As String
            Get
                Return ResourceManager.GetString("action_msbRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear.
        '''</summary>
        Friend ReadOnly Property questionnaire_create() As String
            Get
                Return ResourceManager.GetString("questionnaire_create", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar.
        '''</summary>
        Friend ReadOnly Property questionnaire_modify() As String
            Get
                Return ResourceManager.GetString("questionnaire_modify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen cuestionarios.
        '''</summary>
        Friend ReadOnly Property questionnaire_noQuestionnaires() As String
            Get
                Return ResourceManager.GetString("questionnaire_noQuestionnaires", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar.
        '''</summary>
        Friend ReadOnly Property questionnaireInstance_modify() As String
            Get
                Return ResourceManager.GetString("questionnaireInstance_modify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pendientes.
        '''</summary>
        Friend ReadOnly Property questionnaireInstance_msbPendingItemsCap() As String
            Get
                Return ResourceManager.GetString("questionnaireInstance_msbPendingItemsCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aún tiene tareas pendientes. ¿Desea dejarlas así y salir?.
        '''</summary>
        Friend ReadOnly Property questionnaireInstance_msbPendingItemsMsg() As String
            Get
                Return ResourceManager.GetString("questionnaireInstance_msbPendingItemsMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respuesta incompleta.
        '''</summary>
        Friend ReadOnly Property questionnaireSet_msbRequiredCap() As String
            Get
                Return ResourceManager.GetString("questionnaireSet_msbRequiredCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe seleccionar una operación.
        '''</summary>
        Friend ReadOnly Property questionnaireSet_msbRequiredMsg() As String
            Get
                Return ResourceManager.GetString("questionnaireSet_msbRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen grupos de cuestionarios válidos para este estudio..
        '''</summary>
        Friend ReadOnly Property questionnaireSet_noQuestionnaireSetCap() As String
            Get
                Return ResourceManager.GetString("questionnaireSet_noQuestionnaireSetCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Crear.
        '''</summary>
        Friend ReadOnly Property section_createCap() As String
            Get
                Return ResourceManager.GetString("section_createCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar.
        '''</summary>
        Friend ReadOnly Property section_modifyCap() As String
            Get
                Return ResourceManager.GetString("section_modifyCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen secciones.
        '''</summary>
        Friend ReadOnly Property section_noSectionCap() As String
            Get
                Return ResourceManager.GetString("section_noSectionCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respuesta incompleta.
        '''</summary>
        Friend ReadOnly Property site_msbRequiredCap() As String
            Get
                Return ResourceManager.GetString("site_msbRequiredCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe seleccionar un sitio.
        '''</summary>
        Friend ReadOnly Property site_msbRequiredMsg() As String
            Get
                Return ResourceManager.GetString("site_msbRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen sitios de trabajo.
        '''</summary>
        Friend ReadOnly Property site_noSites() As String
            Get
                Return ResourceManager.GetString("site_noSites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salir.
        '''</summary>
        Friend ReadOnly Property study_exit() As String
            Get
                Return ResourceManager.GetString("study_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respuesta incompleta.
        '''</summary>
        Friend ReadOnly Property study_msbRequiredCap() As String
            Get
                Return ResourceManager.GetString("study_msbRequiredCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe seleccionar un estudio.
        '''</summary>
        Friend ReadOnly Property study_msbRequiredMsg() As String
            Get
                Return ResourceManager.GetString("study_msbRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen estudios registrados..
        '''</summary>
        Friend ReadOnly Property study_noStudies() As String
            Get
                Return ResourceManager.GetString("study_noStudies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respuesta incompleta.
        '''</summary>
        Friend ReadOnly Property subject_msbRequiredCap() As String
            Get
                Return ResourceManager.GetString("subject_msbRequiredCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe seleccionar un sujeto.
        '''</summary>
        Friend ReadOnly Property subject_msbRequiredMsg() As String
            Get
                Return ResourceManager.GetString("subject_msbRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salir.
        '''</summary>
        Friend ReadOnly Property vicoLogin_exit() As String
            Get
                Return ResourceManager.GetString("vicoLogin_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Debe que seleccionar un código y una contraseña para continuar!.
        '''</summary>
        Friend ReadOnly Property vicoLogin_msbBlankNextMsg() As String
            Get
                Return ResourceManager.GetString("vicoLogin_msbBlankNextMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡El código y contraseña que ingresó no son válidos!.
        '''</summary>
        Friend ReadOnly Property vicoLogin_msbValidNextMsg() As String
            Get
                Return ResourceManager.GetString("vicoLogin_msbValidNextMsg", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
