'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QM.PDA.Screens.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El código de autorización ingresado no es válido. Intente de nuevo.
        '''</summary>
        Friend ReadOnly Property correctDateTime_msbWrongCode() As String
            Get
                Return ResourceManager.GetString("correctDateTime_msbWrongCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contacte a soporte técnico para que le provea el código de autorización número {0}..
        '''</summary>
        Friend ReadOnly Property correctDateTime_overrideNote() As String
            Get
                Return ResourceManager.GetString("correctDateTime_overrideNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Lectura inválida! Espere….
        '''</summary>
        Friend ReadOnly Property gps_invalidReading() As String
            Get
                Return ResourceManager.GetString("gps_invalidReading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Satélites insuficientes! Espere….
        '''</summary>
        Friend ReadOnly Property gps_moreSatellites() As String
            Get
                Return ResourceManager.GetString("gps_moreSatellites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esta pantalla necesita una tabla de referencia..
        '''</summary>
        Friend ReadOnly Property name_misconfigurationErrorMsg() As String
            Get
                Return ResourceManager.GetString("name_misconfigurationErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor máximo.
        '''</summary>
        Friend ReadOnly Property question_msbAbsMaxCap() As String
            Get
                Return ResourceManager.GetString("question_msbAbsMaxCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor que ingresó debe ser menor o igual a: {0}.
        '''</summary>
        Friend ReadOnly Property question_msbAbsMaxMsg() As String
            Get
                Return ResourceManager.GetString("question_msbAbsMaxMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor mínimo.
        '''</summary>
        Friend ReadOnly Property question_msbAbsMinCap() As String
            Get
                Return ResourceManager.GetString("question_msbAbsMinCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor que ingresó debe ser mayor o igual a: {0}.
        '''</summary>
        Friend ReadOnly Property question_msbAbsMinMsg() As String
            Get
                Return ResourceManager.GetString("question_msbAbsMinMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Realmente desea regresar?.
        '''</summary>
        Friend ReadOnly Property question_msbConfirmBackMsg() As String
            Get
                Return ResourceManager.GetString("question_msbConfirmBackMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cambio de valor.
        '''</summary>
        Friend ReadOnly Property question_msbConfirmCap() As String
            Get
                Return ResourceManager.GetString("question_msbConfirmCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Esta seguro que desea realizar este cambio?.
        '''</summary>
        Friend ReadOnly Property question_msbConfirmChangeMsg() As String
            Get
                Return ResourceManager.GetString("question_msbConfirmChangeMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Realmente desea continuar?.
        '''</summary>
        Friend ReadOnly Property question_msbConfirmNextMsg() As String
            Get
                Return ResourceManager.GetString("question_msbConfirmNextMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validacion a la medida.
        '''</summary>
        Friend ReadOnly Property question_msbCustomValidationCap() As String
            Get
                Return ResourceManager.GetString("question_msbCustomValidationCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error inesperado.
        '''</summary>
        Friend ReadOnly Property question_msbInputExceptionCap() As String
            Get
                Return ResourceManager.GetString("question_msbInputExceptionCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha habido un error inesperado al procesar su respuesta.
        '''</summary>
        Friend ReadOnly Property question_msbInputExceptionMsg() As String
            Get
                Return ResourceManager.GetString("question_msbInputExceptionMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor máximo aceptable.
        '''</summary>
        Friend ReadOnly Property question_msbPromptOverCap() As String
            Get
                Return ResourceManager.GetString("question_msbPromptOverCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que el valor: {0} es correcto?.
        '''</summary>
        Friend ReadOnly Property question_msbPromptOverMsg() As String
            Get
                Return ResourceManager.GetString("question_msbPromptOverMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor mínimo aceptable.
        '''</summary>
        Friend ReadOnly Property question_msbPromptUnderCap() As String
            Get
                Return ResourceManager.GetString("question_msbPromptUnderCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que el valor: {0} es correcto?.
        '''</summary>
        Friend ReadOnly Property question_msbPromptUnderMsg() As String
            Get
                Return ResourceManager.GetString("question_msbPromptUnderMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pregunta obligatoria.
        '''</summary>
        Friend ReadOnly Property question_msbRequiredCap() As String
            Get
                Return ResourceManager.GetString("question_msbRequiredCap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe ingresar una respuesta a la pregunta.
        '''</summary>
        Friend ReadOnly Property question_msbRequiredMsg() As String
            Get
                Return ResourceManager.GetString("question_msbRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reanudar.
        '''</summary>
        Friend ReadOnly Property timer_resume() As String
            Get
                Return ResourceManager.GetString("timer_resume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar.
        '''</summary>
        Friend ReadOnly Property timer_start() As String
            Get
                Return ResourceManager.GetString("timer_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detener.
        '''</summary>
        Friend ReadOnly Property timer_stop() As String
            Get
                Return ResourceManager.GetString("timer_stop", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
